### ISSUE TITLE
Validation and test not taking all the available data

### ISSUE THREAD

**Issue by david-cortes** [premgopalan/collabtm#2]
When looking at the log file `validation.txt`, I see that the program is taking fewer entries than there are on the file `validation.tsv`.  As a concrete example, I’ve upload some dataset under this link:
https://drive.google.com/open?id=1FzBzQnGU3bQ3ojLIGy9Hby9A6Tcun-JQ

in which the `train.tsv` and `validation.tsv` files are the same, thus I guess there’s no reason to discard any data (unless there is some filter according to minimum number of entries that a user must have or something like that). All users in `train.tsv` have >= 2 items.

The files contain 625315 entries each, but the log says there are 434084 ratings. Same for `test.txt`, wich says there are 62197 entries but the file `test.tsv` contains 96485 entries.

The program was run with the following parameters:
`collabtm -dir /home/david/RRoff -nusers 191770 -ndocs 119448 -nvocab 342260 -k 50`

**Comment by lcharlin** [comment]
By default some docs and their ratings are removed to act as
cold-start documents.

You can change that with the heldout-items-ratio command line option.
E.g., setting it to 0.0 will ensure all docs remain in the training
set.

**Comment by david-cortes** [comment]
Thanks for the answer! Guess that would be a nice addition to the readme section.
